version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - 5433:5432
  app:
    container_name: nest-online-course
    build: 
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 3000:3001
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_LOCAL_PORT=${POSTGRES_LOCAL_PORT}
      - PORT=${PORT}
      - LOCAL_PORT=${LOCAL_PORT}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
      - REFRESH_TOKEN_TIME=${REFRESH_TOKEN_TIME}

volumes:
  pgdata:
    external: true
      